#!/bin/sh
rm -f /tmp/luci-indexcache
#uci track
if ! uci get ucitrack.@fogvdn[-1] >/dev/null 2>&1; then
    cfg_id=$(uci add ucitrack fogvdn)
    uci set ucitrack.$cfg_id.init="fogvdn" 2>/dev/null
    uci commit ucitrack 2>/dev/null
fi
exit 0
